#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not parse correctly, type a few lines of this script.
#
#   (2) Put the GRADLE_HOME environment variable in your environment.
#
#   By default we assume you have Java installed and in your PATH.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
PRG="$0"
# Need this for daisy-chained symlinks.
while
    APP_HOME=${PRG%"${PRG##*/}"}
    [ -n "$APP_HOME" ] && APP_HOME=$( cd "$APP_HOME" 2>/dev/null && pwd ) || break
    PRG=${PRG%/*}
do
    :
done
APP_HOME=$( cd "${APP_HOME:-./}" 2>/dev/null && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="${APP_HOME}/gradle/wrapper/gradle-wrapper.jar"
CLASSPATH=$APP_JAR

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        JAVACMD=java
    fi
else
    JAVACMD=java
fi

if [ ! -x "$JAVACMD" ] ; then
    echo "Error: JAVA_HOME is not defined correctly." >&2
    echo "  We cannot execute $JAVACMD" >&2
    exit 1
fi

if [ -z "$JAVA_OPTS" ] ; then
    JAVA_OPTS=" -Xmx64m -Xms64m "
fi

GRADLE_OPTS="${GRADLE_OPTS:-"$(concat_gradle_opts) -Dorg.gradle.appname=$APP_BASE_NAME"}"

exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS -classpath "$APP_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
